codecov:
  require_ci_to_pass: yes
comment:
  layout: "header,diff,files"
  require_changes: true
  require_base: true
  require_head: true
coverage:
  status:
    project:
      default:
        target: "75%"
        threshold: "0.1%"
        removed_code_behavior: adjust_base
github_checks:
  annotations: true
ignore:
  - "app"
  - "docs"
  - "example_configs"
  - "migration-tool"
  - "scripts"
  - "set-password"
