codecov:
  require_ci_to_pass: yes
comment:
  layout: "condensed_header, diff, condensed_files"
  hide_project_coverage: true
  require_changes: "coverage_drop"
coverage:
  range: "70...100"
  status:
    project:
      default:
        target: "75%"
        threshold: 5
ignore:
  - "app"
  - "docs"
  - "example_configs"
  - "migration-tool"
  - "scripts"
  - "set-password"
