[package]
name = "lldap_validation"
version = "0.6.0"
authors = ["Simon Broeng Jensen <sbj@cwconsult.dk>"]
description = "Validation logic for LLDAP"
edition = "2021"
homepage.workspace = true
license.workspace = true
repository.workspace = true
