//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use lldap_domain::types::Serialized;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "plugin_key_values")]
pub struct Model {
    #[sea_orm(
        column_name = "plugin_key_scope",
        primary_key,
        auto_increment = false,
        column_type = "Text"
    )]
    pub scope: String,
    #[sea_orm(
        column_name = "plugin_key",
        primary_key,
        auto_increment = false,
        column_type = "Text"
    )]
    pub key: String,
    #[sea_orm(column_name = "plugin_key_value")]
    pub value: Serialized,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
