name: Release Bot

on:
  release:
    types: [published]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: nflaig/release-comment-on-pr@master
        with:
          token: ${{ secrets.RELEASE_BOT_TOKEN }}
          message: |
            Thank you everyone for the contribution!
            This feature is now available in the latest release, [${releaseTag}](${releaseUrl}).
            You can support LLDAP by starring our repo, contributing some configuration examples and becoming a sponsor.
